name: pichuruco
description: Cofrinho digital compartilhado para casais.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.18.1
  lottie: ^2.7.0
  simple_animations: ^5.0.0
  animations: ^2.0.7
  confetti: ^0.7.0
  animated_background: ^2.0.0

  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.2

  # Armazenamento local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # Exportação CSV
  csv: ^5.0.2

  # Conectividade
  connectivity_plus: ^5.0.2

  # Compartilhamento
  share_plus: ^7.2.1

  # Gerenciamento de estado (usaremos Provider inicialmente)
  provider: ^6.1.2

  # Firebase Options (gerado pelo Firebase CLI)
  #firebase_options: # será gerado manualmente mais adiante

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
