name: pichuruco
description: Cofrinho digital compartilhado para casais.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  intl: ^0.20.2
  lottie: ^3.3.1
  simple_animations: ^5.0.0
  animations: ^2.0.7
  confetti: ^0.8.0
  animated_background: ^2.0.0



  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11

  # Armazenamento local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2

  # Exportação CSV
  csv: ^6.0.0
  file_picker: ^10.2.0



  # Exportação PDF
  pdf: ^3.10.4
  printing: ^5.11.0

  # Conectividade
  connectivity_plus: ^6.1.4

  # Compartilhamento
  share_plus: ^11.0.0

  # Gerenciamento de estado (usaremos Provider inicialmente)
  provider: ^6.1.2

  # Firebase Options (gerado pelo Firebase CLI)
  #firebase_options: # será gerado manualmente mais adiante

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
