// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY8dSfqdLMM659HJ2-EKYaVDqkJTYHra4',
    appId: '1:622502627516:web:5a766ac6bd94a1abf1a8b9',
    messagingSenderId: '622502627516',
    projectId: 'pichuruco',
    authDomain: 'pichuruco.firebaseapp.com',
    storageBucket: 'pichuruco.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVjEVDOwUvE_6gbTmmmGZriC4efqUnYyA',
    appId: '1:622502627516:android:10e310a1eaafdbb9f1a8b9',
    messagingSenderId: '622502627516',
    projectId: 'pichuruco',
    storageBucket: 'pichuruco.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABIPRxBkaB6dUm79s-ajdr41Ma6sflxUw',
    appId: '1:622502627516:ios:577ddb5455d6ced9f1a8b9',
    messagingSenderId: '622502627516',
    projectId: 'pichuruco',
    storageBucket: 'pichuruco.firebasestorage.app',
    iosBundleId: 'com.example.pichuru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABIPRxBkaB6dUm79s-ajdr41Ma6sflxUw',
    appId: '1:622502627516:ios:577ddb5455d6ced9f1a8b9',
    messagingSenderId: '622502627516',
    projectId: 'pichuruco',
    storageBucket: 'pichuruco.firebasestorage.app',
    iosBundleId: 'com.example.pichuru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY8dSfqdLMM659HJ2-EKYaVDqkJTYHra4',
    appId: '1:622502627516:web:22a8170988aa26b6f1a8b9',
    messagingSenderId: '622502627516',
    projectId: 'pichuruco',
    authDomain: 'pichuruco.firebaseapp.com',
    storageBucket: 'pichuruco.firebasestorage.app',
  );

}